"""empty message

Revision ID: c09ea03afe28
Revises: 
Create Date: 2017-05-18 08:30:26.108465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09ea03afe28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrate_version')
    op.drop_index('ix_article_author', table_name='article')
    op.drop_index('ix_article_body', table_name='article')
    op.drop_index('ix_article_read_cnt', table_name='article')
    op.drop_index('ix_article_title', table_name='article')
    op.drop_column('article', 'read_cnt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('read_cnt', sa.INTEGER(), nullable=True))
    op.create_index('ix_article_title', 'article', ['title'], unique=1)
    op.create_index('ix_article_read_cnt', 'article', ['read_cnt'], unique=1)
    op.create_index('ix_article_body', 'article', ['body'], unique=1)
    op.create_index('ix_article_author', 'article', ['author'], unique=1)
    op.create_table('migrate_version',
    sa.Column('repository_id', sa.VARCHAR(length=250), nullable=False),
    sa.Column('repository_path', sa.TEXT(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('repository_id')
    )
    # ### end Alembic commands ###
